# Generated by Django 3.2.25 on 2025-01-03 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0012_alter_ticket_remark"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="helpers",
            field=models.JSONField(default=list, verbose_name="协助人"),
        ),
    ]
