# Generated by Django 3.2.25 on 2024-11-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redis_modules", "0003_alter_tbredismodulesupport_so_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClusterRedisModuleAssociate",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cluster_id", models.IntegerField(default=0, verbose_name="集群ID")),
                ("module_names", models.JSONField(default=list, verbose_name="module名称列表")),
            ],
            options={
                "verbose_name": "Cluster Redis module关联",
                "verbose_name_plural": "Cluster Redis module关联",
                "db_table": "tb_cluster_redis_module_associate",
                "unique_together": {("cluster_id",)},
            },
        ),
    ]
